[package]
name = "pinpoint_shooting"
version = "0.1.0"
authors = ["Jeff Culverhouse <jeff@graystorm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.*"
config = "0.9.3"
lazy_static = "1.3.0"
log = "0.4.7"
simple_logger = "1.3.0"
handlebars-iron = "0.27.0"
serde_derive = "1.0.94"
serde = "1.0.94"
