[development]
address = "0.0.0.0"
port = 3000
workers = 4
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
template_dir = "./src/view/templates"

[staging]
address = "0.0.0.0"
port = 80
workers = 8
keep_alive = 5
log = "normal"
limits = { forms = 32768 }
template_dir = "./src/view/templates"

[production]
address = "0.0.0.0"
port = 80
workers = 16
keep_alive = 5
log = "critical"
limits = { forms = 32768 }
template_dir = "./src/view/templates"
