[development]
address = "127.0.0.1"
port = 3000
workers = 4
keep_alive = 5
log = "off"
limits = { forms = 32768 }
template_dir = "./src/view/templates"

[staging]
address = "127.0.0.1"
port = 3000
workers = 8
keep_alive = 5
log = "off"
limits = { forms = 32768 }
template_dir = "./src/view/templates"

[production]
address = "127.0.0.1"
port = 3000
workers = 16
keep_alive = 5
log = "off"
limits = { forms = 32768 }
template_dir = "./src/view/templates"
