[server]
run_level = "production"

[logconfig]
type = "file"
format = "full"
source_location = "module_and_line"
timezone = "local"
level = "debug"
path = "log/app.log"
rotate_size = 1073741824
rotate_keep = 30

[webservice]
bind_address = "0.0.0.0"
bind_port = 80
