[server]
run_level = "staging"

[sessions]
expire = 10080

[logconfig]
level = "trace"
applog_path = "log/app.log"
weblog_path = "log/rocket.log"

[webservice]
bind_address = "127.0.0.1"
bind_port = 3000
